[[constraint]]
  branch = "master"
  name = "github.com/VividCortex/mysqlerr"

[[constraint]]
  branch = "master"
  name = "github.com/WatchBeam/clock"

[[constraint]]
  name = "github.com/beevik/etree"
  version = "1.0.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/e-dard/netbug"

[[constraint]]
  name = "github.com/elazarl/go-bindata-assetfs"
  version = "1.0.0"

[[constraint]]
  name = "github.com/gomodule/redigo"
  version = "2.0.0"

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.6.0"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  name = "github.com/igm/sockjs-go"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  branch = "master"
  name = "github.com/kolide/goose"

[[constraint]]
  branch = "master"
  name = "github.com/kolide/kit"

[[constraint]]
  branch = "master"
  name = "github.com/kolide/launcher"

[[constraint]]
  branch = "master"
  name = "github.com/kolide/osquery-go"

[[constraint]]
  branch = "master"
  name = "github.com/patrickmn/sortutil"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/russellhaering/gosaml2"

[[constraint]]
  name = "github.com/russellhaering/goxmldsig"
  revision = "b7efc6231e45b10bfd779852831c8bb59b350ec5"

[[constraint]]
  name = "github.com/spf13/cast"
  version = "1.1.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.9.2"

[[constraint]]
  name = "gopkg.in/natefinch/lumberjack.v2"
  version = "2.1.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[prune]
  go-tests = true
  unused-packages = true
