services:
  - name: fleet
    plan: standard
    type: web
    runtime: image
    image:
      url: 'fleetdm/fleet:latest'
    preDeployCommand: "fleet prepare --no-prompt=true db"
    healthCheckPath: /healthz
    disk:
      name: installers
      mountPath: /opt/fleet/installers
      sizeGB: 10
    envVars:
      - key: FLEET_SOFTWARE_INSTALLER_STORE_DIR
        value: '/opt/fleet/installers'
      - key: FLEET_SERVER_PRIVATE_KEY
        generateValue: true
      - key: FLEET_MYSQL_ADDRESS
        fromService:
          name: fleet-mysql
          type: pserv
          property: hostport
      - key: FLEET_MYSQL_DATABASE
        fromService:
          name: fleet-mysql
          type: pserv
          envVarKey: MYSQL_DATABASE
      - key: FLEET_MYSQL_PASSWORD
        fromService:
          name: fleet-mysql
          type: pserv
          envVarKey: MYSQL_PASSWORD
      - key: FLEET_MYSQL_USERNAME
        fromService:
          name: fleet-mysql
          type: pserv
          envVarKey: MYSQL_USER
      - key: FLEET_REDIS_ADDRESS
        fromService:
          name: fleet-redis
          type: redis
          property: connectionString
      - key: FLEET_SERVER_TLS
        value: 'false'
      - key: PORT
        value: 8080

  - name: fleet-mysql
    plan: standard
    type: pserv
    runtime: docker
    repo: https://github.com/render-examples/mysql
    disk:
      name: mysql
      mountPath: /var/lib/mysql
      sizeGB: 10
    envVars:
      - key: MYSQL_DATABASE
        value: fleet
      - key: MYSQL_PASSWORD
        generateValue: true
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: MYSQL_USER
        value: fleet

  - name: fleet-redis
    plan: starter # May use free plan for testing or short-lived deployments
    type: redis
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []
