name: routes
examples: |-
  Identify static routes
  
  ```
  SELECT destination, interface, type FROM routes WHERE type='static';
  ```
columns:
  - name: hopcount
    platforms:
      - linux
      - darwin
