version: 2
jobs:
  build-go:
    docker:
      - image: golang:1.12
    working_directory: /go/src/github.com/kolide/fleet
    steps: &stepsgo
      - checkout
      - restore_cache:
          keys:
            - vendor-cache-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
            - vendor-cache-{{ .Branch }}
            - vendor-cache

      - run: make deps-go
      - save_cache:
          key: vendor-cache-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - save_cache:
          key: vendor-cache-{{ .Branch }}
          paths:
            - vendor
      - save_cache:
          key: vendor-cache
          paths:
            - vendor
      - run: make generate-go
      - run: make lint-go
      - run: make test-go
      - run: make build

  build-js:
    docker:
      - image: node:10.16.0
    steps: &stepsjs
      - checkout
      - run: make deps-js
      - run: make generate-js
      - run: make lint-js
      - run: make test-js

workflows:
  version: 2
  build:
    jobs:
      - build-go
      - build-js
