blank_issues_enabled: true
contact_links:
  - name: Chat with other developers
    url: https://osquery.slack.com/join/shared_invite/zt-h29zm0gk-s2DBtGUTW4CFel0f0IjTEw#/
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://fleetdm.com/documentation
    about: Read about how to use, deploy, and configure Fleet.

