---
version: '2'

x-default-settings:
  volumes: &default-volumes
    - ./fleet.crt:/etc/osquery/fleet.crt
    - ./example_osquery.flags:/etc/osquery/osquery.flags
  environment: &default-environment
    ENROLL_SECRET: "${ENROLL_SECRET:?ENROLL_SECRET must be set for server authentication}"
  command: &default-command osqueryd --flagfile=/etc/osquery/osquery.flags --tls_hostname=${FLEET_SERVER:-host.docker.internal:8080}
  ulimits: &default-ulimits
    core:
      hard:  1000000000
      soft:  1000000000
  extra_hosts: &extra-hosts
    - "host.docker.internal:host-gateway"

services:
  ubuntu16-osquery:
    image: "dactiv/osquery:4.5.1-ubuntu16.04"
    volumes: *default-volumes
    environment: *default-environment
    command: *default-command
    ulimits: *default-ulimits
    extra_hosts: *extra-hosts

  ubuntu18-osquery:
    image: "dactiv/osquery:4.5.1-ubuntu18.04"
    volumes: *default-volumes
    environment: *default-environment
    command: *default-command
    ulimits: *default-ulimits
    extra_hosts: *extra-hosts

  ubuntu20-osquery:
    image: "dactiv/osquery:4.5.1-ubuntu20.04"
    platform: linux/x86_64
    volumes: *default-volumes
    environment: *default-environment
    command: *default-command
    ulimits: *default-ulimits
    extra_hosts: *extra-hosts

  centos6-osquery:
    image: "dactiv/osquery:4.5.1-centos6"
    volumes: *default-volumes
    environment: *default-environment
    command: *default-command
    ulimits: *default-ulimits
    extra_hosts: *extra-hosts

  centos7-osquery:
    image: "dactiv/osquery:4.5.1-centos7"
    volumes: *default-volumes
    environment: *default-environment
    command: *default-command
    ulimits: *default-ulimits
    extra_hosts: *extra-hosts

  centos8-osquery:
    image: "dactiv/osquery:4.5.1-centos8"
    volumes: *default-volumes
    environment: *default-environment
    command: *default-command
    ulimits: *default-ulimits
    extra_hosts: *extra-hosts
