name: Collect engineering metrics test

on:
  push:
    branches:
      - main
      - patch-*
      - prepare-*
    paths:
      - '.github/actions/eng-metrics/**'
  pull_request:
    paths:
      - '.github/actions/eng-metrics/**'
  workflow_dispatch:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id}}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Test Engineering Metrics Action
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2

      - name: Setup Node.js 20
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # 4.4.0
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: '.github/actions/eng-metrics/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: .github/actions/eng-metrics

      - name: Run linting
        run: npm run lint
        working-directory: .github/actions/eng-metrics

      - name: Run tests
        run: npm test
        working-directory: .github/actions/eng-metrics
        env:
          NODE_ENV: test
