# This workflow applies the latest MDM profiles to the workstations team.
#
# It runs automatically when a file is changed in /mdm_profiles.
name: Configuration profiles demo

on:
  pull_request:
    branches:
      - main
    paths:
      - "mdm_profiles_demo/**.mobileconfig"
      - ".github/workflows/configuration_profiles_demo.yml"
  workflow_dispatch: # Manual

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id}}
  cancel-in-progress: true

defaults:
  run:
    # fail-fast using bash -eo pipefail. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

permissions:
  contents: read

env:
  DOGFOOD_API_TOKEN: ${{ secrets.DOGFOOD_API_TOKEN }}
  DOGFOOD_URL: ${{ secrets.DOGFOOD_URL }}
  CLOUD_MANAGEMENT_ENROLLMENT_TOKEN: ${{ secrets.CLOUD_MANAGEMENT_ENROLLMENT_TOKEN }}

jobs:
  apply-profiles:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Apply configuration profiles and updates
        uses: fleetdm/fleet-mdm-gitops@026ee84a69cb89c869fedbe27c969bf89def418b
        with:
          FLEET_API_TOKEN: $DOGFOOD_API_TOKEN
          FLEET_URL: $DOGFOOD_URL
          FLEET_TEAM_NAME: MDOYVR Demo
          MDM_CONFIG_REPO: fleetdm/fleet
          MDM_CONFIG_DIRECTORY: mdm_profiles_demo
          MAC_OS_MIN_VERSION: "13.4.0"
          MAC_OS_VERSION_DEADLINE: 2023-07-01
          MAC_OS_ENABLE_DISK_ENCRYPTION: true
