name: Check for bad links in documentation

on:
  pull_request:
    paths:
    # Only run on changes to .md files -- this check is too flakey to run on every PR
    - '**.md'
  workflow_dispatch: # Manual
  schedule:
  - cron: '0 6 * * *' # Nightly 6AM UTC

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master
    - uses: gaurav-nelson/github-action-markdown-link-check@9710f0fec812ce0a3b98bef4c9d842fc1f39d976 # v1.0.13
      with:
        use-quiet-mode: 'yes'
        config-file: .github/workflows/markdown-link-check-config.json
        base-branch: ${{ github.base_ref }}
