name: Generate osqueryd.app.tar.gz for Orbit

on:
  push:
    branches:
      - main
    paths:
      # The workflow can be triggered by modifying OSQUERY_VERSION env.
      - '.github/workflows/generate-osqueryd-app-tar-gz.yml'
  pull_request:
    paths:
      # The workflow can be triggered by modifying OSQUERY_VERSION env.
      - '.github/workflows/generate-osqueryd-app-tar-gz.yml'
  workflow_dispatch:

env:
  OSQUERY_VERSION: 5.2.2

jobs:
  generate:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate osqueryd.app.tar.gz
        run: |
          mkdir osqueryd-app-tar-gz
          make osqueryd-app-tar-gz out-path=./osqueryd-app-tar-gz version=$OSQUERY_VERSION

      - name: Upload osqueryd.app.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: osqueryd.app.tar.gz
          path: ./osqueryd-app-tar-gz
