name: golangci-lint

on:
  push:
    branches:
      - main
      - patch-*
    paths:
      - '**.go'
  pull_request:
    paths:
      - '**.go'
      - '.github/workflows/golangci-lint.yml'
  workflow_dispatch: # Manual

defaults:
  run:
    # fail-fast using bash -eo pipefail. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

permissions:
  contents: read

jobs:
  golangci:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # for actions/checkout to fetch pull requests
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2

      - uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f
        with:
          go-version: '1.19.1'

      - name: Run go lint
        run: |
          # The following packages are needed to build Fleet Desktop on Ubuntu.
          sudo apt install -y gcc libgtk-3-dev libayatana-appindicator3-dev
          # Don't forget to update
          # docs/Contributing/Testing-and-local-development.md when this
          # version changes
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.47.3
          make lint-go
