name: Update Osquery versions in UI

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  update-versions:
    permissions:
      contents: write # for peter-evans/create-pull-request to create branch
      pull-requests: write # for peter-evans/create-pull-request to create a PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Set up Python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: pip install requests==2.32.3 --hash=sha256:7f22e2e5c3c90c0c1c5ca4e7a1ac79b88cab99b2f9c261a4b0e0c2f5f58b1ba4
      - name: Update Osquery versions in UI
        run: python .github/scripts/update_osquery_versions.py
      - name: PR changes
        uses: peter-evans/create-pull-request@4e1beaa7521e8b457b572c090b25bd3db56bf1c5 # v5.0.3
        with:
          commit-message: Update MIN_OSQUERY_VERSION_OPTIONS
          title: "Fleet UI: Update osquery version options"
          body: "Automated update of MIN_OSQUERY_VERSION_OPTIONS with any new osquery release. (Note: This automatic update is the solution to issue #21431)"
          branch: update-osquery-versions
          delete-branch: true
